-- Azul Baronis -- English localization.

INSERT OR REPLACE INTO Language_en_US (Tag, Text) VALUES
('TXT_KEY_UNIT_AZUL_INTERNAL_DISABLED', 'Unavailable Azul Hull'),
('TXT_KEY_CIV_AZUL_BARONIS_DESC', 'Azul Baronis'),
('TXT_KEY_CIV_AZUL_BARONIS_SHORT_DESC', 'Azul Baronis'),
('TXT_KEY_CIV_AZUL_BARONIS_ADJECTIVE', 'Azul'),
('TXT_KEY_CIV_AZUL_BARONIS_PEDIA', 'A nomadic starfaring command whose entire military doctrine is organized around a Mothership and a small family of permanently modernizing warships.'),
('TXT_KEY_CIV_AZUL_BARONIS_STRATEGY', 'Azul fields no conventional military. Use fast Fighters to explore and screen, add Destroyers in the Renaissance, and commit era-limited Testudons as super-heavy anchors. Protect the original Mothership while converting its Production into turrets or an instant-kill Main Cannon shot.'),
('TXT_KEY_CIV5_DOM_AZUL_BARONIS_TEXT', 'The fleet is awake. From the Mothership, one will guides many hulls across land, sea, and eventually the highest mountains and deepest ocean. Choose your vessel, preserve the core, and let no age make your ships obsolete.'),

('TXT_KEY_LEADER_AZUL_THE_PLAYER', 'The Player'),
('TXT_KEY_LEADER_AZUL_THE_PLAYER_PEDIA', 'The Player is a working leader identity intentionally isolated behind one localization key for easy renaming.'),
('TXT_KEY_CIVILOPEDIA_LEADERS_AZUL_THE_PLAYER_NAME', 'The Player'),
('TXT_KEY_CIVILOPEDIA_LEADERS_AZUL_THE_PLAYER_SUBTITLE', 'Fleetmind of Azul Baronis'),
('TXT_KEY_CIVILOPEDIA_LEADERS_AZUL_THE_PLAYER_LIVED', 'Unknown'),
('TXT_KEY_CIVILOPEDIA_LEADERS_AZUL_THE_PLAYER_HEADING_1', 'The Command Vessel'),
('TXT_KEY_CIVILOPEDIA_LEADERS_AZUL_THE_PLAYER_TEXT_1', 'One eligible Fighter or Destroyer carries the Player directly. Its advantage is control and maneuver, never stronger weaponry.'),
('TXT_KEY_LEADER_AZUL_FIRSTGREETING_1', 'A signal resolves into a single voice. I am the Player. These ships are Azul Baronis. State your vector.'),
('TXT_KEY_LEADER_AZUL_GREETING_FRIENDLY_1', 'Your signal is recognized. Approach.'),
('TXT_KEY_LEADER_AZUL_GREETING_NEUTRAL_1', 'The fleet is listening.'),
('TXT_KEY_LEADER_AZUL_DEFEATED_1', 'The core goes dark. The fleet remembers.'),

('TXT_KEY_TRAIT_AZUL_ONE_SHIP_AMONG_MANY_SHORT', 'One Ship Among Many'),
('TXT_KEY_TRAIT_AZUL_ONE_SHIP_AMONG_MANY', 'Exactly one Fighter or Destroyer is Player Controlled: +1 [ICON_MOVES] Movement, +1 Sight, +25% Experience, and Afterburner. Azul military hulls modernize to exact Era statistics, hover across land and Coast, gain Ocean access at Astronomy and Mountain access at Flight, and replace the conventional military tree.'),

('TXT_KEY_CITY_AZUL_MOTHERSHIP', 'Mothership'),
('TXT_KEY_CITY_AZUL_AZURE_REACH', 'Azure Reach'),
('TXT_KEY_CITY_AZUL_BLUE_SHIFT', 'Blue Shift'),
('TXT_KEY_CITY_AZUL_PERIAPSIS', 'Periapsis'),
('TXT_KEY_CITY_AZUL_COLD_ORBIT', 'Cold Orbit'),
('TXT_KEY_CITY_AZUL_VECTOR_NINE', 'Vector Nine'),
('TXT_KEY_CITY_AZUL_EVENT_HORIZON', 'Event Horizon'),
('TXT_KEY_CITY_AZUL_ION_WAKE', 'Ion Wake'),
('TXT_KEY_CITY_AZUL_OUTER_SCREEN', 'Outer Screen'),
('TXT_KEY_CITY_AZUL_LAST_LIGHT', 'Last Light'),
('TXT_KEY_SPY_AZUL_ECHO', 'Echo'),
('TXT_KEY_SPY_AZUL_VECTOR', 'Vector'),
('TXT_KEY_SPY_AZUL_LUMEN', 'Lumen'),
('TXT_KEY_SPY_AZUL_APOGEE', 'Apogee'),

('TXT_KEY_BUILDING_AZUL_MOTHERSHIP_CORE', 'Mothership Core'),
('TXT_KEY_BUILDING_AZUL_MOTHERSHIP_CORE_HELP', 'Retains the Palace''s +3 Production, +3 Science, +3 Gold, and +1 Culture. Also provides +50 City Hit Points, +15% City Ranged Strike Strength, and +1 Sight. The original Capital alone can charge the Main Cannon and construct deployable Defensive Turrets.'),
('TXT_KEY_BUILDING_AZUL_MOTHERSHIP_CORE_STRATEGY', 'The Mothership Core is bound to Azul''s original Capital. Losing that city destroys its turrets and clears both production batteries; an emergency Capital receives only an ordinary Palace.'),
('TXT_KEY_BUILDING_AZUL_MOTHERSHIP_CORE_PEDIA', 'The Core is at once palace, vessel, fortress, and continuity of command. Its great weapons do not draw on ordinary yields: they consume the Mothership''s Production directly.'),

('TXT_KEY_PROCESS_AZUL_CHARGE_MAIN_CANNON', 'Charge Main Cannon'),
('TXT_KEY_PROCESS_AZUL_CHARGE_MAIN_CANNON_HELP', 'Converts 100% of Mothership Production, including fractional output, into persistent Main Cannon Energy. At full charge, the Fleet Systems panel can destroy one visible hostile combat unit within 5 tiles.'),
('TXT_KEY_PROCESS_AZUL_CHARGE_MAIN_CANNON_STRATEGY', 'Charge during war or when a valuable target is expected. Progress is retained when production changes.'),
('TXT_KEY_PROCESS_AZUL_CONSTRUCT_TURRET', 'Construct Defensive Turret'),
('TXT_KEY_PROCESS_AZUL_CONSTRUCT_TURRET_HELP', 'Converts 100% of Mothership Production into one persistent Defensive Turret construction meter. Only one completed undeployed turret may be stored.'),
('TXT_KEY_PROCESS_AZUL_CONSTRUCT_TURRET_STRATEGY', 'Maintain a screen of up to four stationary turrets around the Mothership.'),

('TXT_KEY_UNIT_AZUL_FIGHTER', 'Fighter'),
('TXT_KEY_UNIT_AZUL_FIGHTER_HELP', 'Fast range-1 spacecraft. Moves after attacking, ignores enemy Zone of Control, and may capture adjacent defeated cities through Fleet Systems. Dogfighter grants +25% ranged defense and a 10% complete evade chance while Movement remains.'),
('TXT_KEY_UNIT_AZUL_FIGHTER_STRATEGY', 'Use Fighters for exploration, flanking, pursuit, and mobile ranged screens. Their exact Combat, Ranged Combat, and Production values modernize every Era.'),
('TXT_KEY_UNIT_AZUL_FIGHTER_PEDIA', 'The smallest common Azul hull is never obsolete. Its pilot and name survive every internal refit.'),
('TXT_KEY_UNIT_AZUL_DESTROYER', 'Destroyer'),
('TXT_KEY_UNIT_AZUL_DESTROYER_HELP', 'Range-2 heavy spacecraft. Moves after attacking. Choose its normal Forward Beam or a range-3, indirect Homing Bomb at 115% Ranged Strength with a 3-turn cooldown.'),
('TXT_KEY_UNIT_AZUL_DESTROYER_STRATEGY', 'Use the Forward Beam against nearby targets and save Homing Bombs for obstructed or high-defense targets. Either weapon consumes the turn''s attack.'),
('TXT_KEY_UNIT_AZUL_DESTROYER_PEDIA', 'The Destroyer carries enough reactor volume to alternate between a direct forward beam and self-guiding high-energy ordnance.'),
('TXT_KEY_UNIT_AZUL_TESTUDON', 'Testudon'),
('TXT_KEY_UNIT_AZUL_TESTUDON_HELP', 'Range-3 super-heavy spacecraft. Cannot attack after moving or move after attacking. Its Focused Beam ignores half of positive defensive modifiers. Takes 20% less ranged damage, cannot retreat, and cannot be captured or converted. Capacity rises from 1 in Industrial to 4 in Information.'),
('TXT_KEY_UNIT_AZUL_TESTUDON_STRATEGY', 'Position Testudons deliberately before firing. They are expensive, era-capped anchors suited to fortified targets.'),
('TXT_KEY_UNIT_AZUL_TESTUDON_PEDIA', 'Testudon hulls trade nearly all tactical speed for capacitors, armor, and a beam capable of boring through layered defenses.'),
('TXT_KEY_UNIT_AZUL_DEFENSIVE_TURRET', 'Defensive Turret'),
('TXT_KEY_UNIT_AZUL_DEFENSIVE_TURRET_HELP', 'Stationary range-2 Mothership defense. Deployed manually within 3 tiles, limited to four, and modernized every Era. Cannot capture cities.'),
('TXT_KEY_UNIT_AZUL_DEFENSIVE_TURRET_STRATEGY', 'Deploy turrets to protect approaches to the original Mothership.'),
('TXT_KEY_UNIT_AZUL_DEFENSIVE_TURRET_PEDIA', 'A turret is a compact ship reactor and weapon assembly fused permanently to its deployment point.'),
('TXT_KEY_UNIT_AZUL_FLEET_COMMANDER', 'Fleet Commander'),
('TXT_KEY_UNIT_AZUL_FLEET_COMMANDER_HELP', 'Replaces the Great General and retains its aura, generation, stacking, and Citadel action. Has 3 Movement and uses Azul hovering traversal, but follows normal Zone of Control rules.'),
('TXT_KEY_UNIT_AZUL_FLEET_COMMANDER_STRATEGY', 'Support the fleet exactly as a Great General supports a land army. Citadels remain restricted to normally valid tiles.'),
('TXT_KEY_UNIT_AZUL_FLEET_COMMANDER_PEDIA', 'Fleet Commanders coordinate formations without displacing the singular Player Controlled vessel.'),

('TXT_KEY_PROMOTION_AZUL_HOVER', 'Hovering Spaceframe'),
('TXT_KEY_PROMOTION_AZUL_HOVER_HELP', 'May traverse land and water without embarking; all traversable tiles cost 1 Movement. Ocean requires Astronomy and Mountains require Flight.'),
('TXT_KEY_PROMOTION_AZUL_MOVE_AFTER_ATTACK', 'Vector Thrusters'),
('TXT_KEY_PROMOTION_AZUL_MOVE_AFTER_ATTACK_HELP', 'May move after making a ranged attack.'),
('TXT_KEY_PROMOTION_AZUL_DOGFIGHTER', 'Dogfighter'),
('TXT_KEY_PROMOTION_AZUL_DOGFIGHTER_HELP', 'Ignores enemy Zone of Control. While Movement remains, gains +25% defense and a 10% chance to evade ranged attacks completely.'),
('TXT_KEY_PROMOTION_AZUL_PLAYER_CONTROLLED', '★ Player Controlled'),
('TXT_KEY_PROMOTION_AZUL_PLAYER_CONTROLLED_HELP', '+1 Movement, +1 Sight, +25% Experience, and access to Afterburner. Provides no Combat Strength.'),
('TXT_KEY_PROMOTION_AZUL_AFTERBURNER_ACTIVE', 'Afterburner Engaged'),
('TXT_KEY_PROMOTION_AZUL_AFTERBURNER_ACTIVE_HELP', 'Afterburner was engaged this turn. The vessel gained bonus Movement and consumed its attack.'),
('TXT_KEY_PROMOTION_AZUL_DOGFIGHTER_DEFENSE', 'Dogfighter Response'),
('TXT_KEY_PROMOTION_AZUL_DOGFIGHTER_DEFENSE_HELP', '+25% defense against this ranged attack.'),
('TXT_KEY_PROMOTION_AZUL_DOGFIGHTER_EVADE', 'Evasive Vector'),
('TXT_KEY_PROMOTION_AZUL_DOGFIGHTER_EVADE_HELP', 'This ranged attack deals no damage.'),
('TXT_KEY_PROMOTION_AZUL_TESTUDON_RANGED_REDUCTION', 'Super-Heavy Damage Control'),
('TXT_KEY_PROMOTION_AZUL_TESTUDON_RANGED_REDUCTION_HELP', 'Takes exactly 20% less damage from this ranged attack.'),
('TXT_KEY_PROMOTION_AZUL_SUPERHEAVY_HULL', 'Super-Heavy Hull'),
('TXT_KEY_PROMOTION_AZUL_SUPERHEAVY_HULL_HELP', 'Takes 20% less damage from ranged attacks and cannot be forced to retreat.'),
('TXT_KEY_PROMOTION_AZUL_UNCONVERTIBLE', 'Secured Command Core'),
('TXT_KEY_PROMOTION_AZUL_UNCONVERTIBLE_HELP', 'Cannot be captured, stolen, or converted.'),
('TXT_KEY_PROMOTION_AZUL_STATIONARY_TURRET', 'Hardpoint Anchors'),
('TXT_KEY_PROMOTION_AZUL_STATIONARY_TURRET_HELP', 'Cannot move or capture cities, but can make one ranged attack each turn after deployment.'),
('TXT_KEY_PROMOTION_AZUL_OCEAN_ACCESS', 'Astronomical Navigation'),
('TXT_KEY_PROMOTION_AZUL_OCEAN_ACCESS_HELP', 'May enter Ocean.'),
('TXT_KEY_PROMOTION_AZUL_MOUNTAIN_ACCESS', 'Flight Vectoring'),
('TXT_KEY_PROMOTION_AZUL_MOUNTAIN_ACCESS_HELP', 'May enter and end a turn on Mountains.'),
('TXT_KEY_PROMOTION_AZUL_HOMING_BOMB_ACTIVE', 'Homing Bomb'),
('TXT_KEY_PROMOTION_AZUL_HOMING_BOMB_ACTIVE_HELP', '+1 Range, +15% Ranged Strength, and ignores line of sight while firing the Homing Bomb.'),
('TXT_KEY_PROMOTION_AZUL_BEAM_COMP', 'Targeting Compensation'),
('TXT_KEY_PROMOTION_AZUL_BEAM_COMP_HELP', 'Temporary attack compensation for ignored defensive modifiers.'),

('TXT_KEY_CIV5_AZUL_BARONIS_TITLE', 'Azul Baronis'),
('TXT_KEY_CIV5_AZUL_BARONIS_HEADING_1', 'The Fleet'),
('TXT_KEY_CIV5_AZUL_BARONIS_TEXT_1', 'Azul Baronis rejects the ordinary military upgrade tree. Its named hulls persist, preserve their experience, and refit to exact statistics whenever the fleet enters a new Era.');
